---
- hosts: all
  user: root
  vars:
    createuser: 'test'
    createpassword: 'TESTpassword123!'

  tasks:
    - name: Setup | Create user
      command: useradd -m {{ createuser }} -s /bin/bash
      args:
        creates: "/home/{{ createuser }}"
      become: true

    - name: Setup | Set user password
      shell: usermod -p $(echo '{{ createpassword }}' | openssl passwd -1 -stdin) {{ createuser }}
      become: true

    - name: Setup | Authorized key upload
      authorized_key:
        user: "{{ createuser }}"
        key: "{{ lookup('file', '/ddevops/ansible-playbooks/keys/' + createuser + '.pub') }}"
        path: "/home/{{ createuser }}/.ssh/authorized_keys"
        manage_dir: no
      become: true

    - name: Sudoers | Update sudoers file and validate
      lineinfile:
        dest: "/etc/sudoers"
        insertafter: EOF
        line: "{{ createuser }} ALL=(ALL) NOPASSWD:ALL,!RESTRICT,!RESTRICT_ACCESS"
        regexp: "{{ createuser }} ALL=(ALL) NOPASSWD:ALL,!RESTRICT,!RESTRICT_ACCESS"
        state: present
      become: true

    - name: Updating Bash Profile
      template:
        src: "/ddevops/ansible-playbooks/templates/devops_bashrc.j2"
        dest: "/home/{{ createuser }}/.bashrc"
        #remote_src: true
      become: true
