- hosts: all
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Ensure python3-apt package is installed
      package:
        name: python3-apt
        state: present

    - name: Purge Python 3 if present
      apt:
        name: python3
        state: absent
        purge: yes

    - name: Install Python 3
      apt:
        name: python3
        state: present

  vars:
    packages_to_uninstall:
      - zabbix-agent
      - monit
      - iftop
      - zip
      - software-properties-common
      - htop
      - lolcat
      - bzip2
      - vnstat
      - rsnapshot
      - git
      - mysecureshell
      - snapd
      - lynx
      - lz4
      - mawk
      - figlet
      - memcached
      - mime-support
      - mount
      - multipath-tools
      - mytop
      - net-tools
      - nmap
      - nodejs
      - npm
      - curl
