- hosts: all
  user: root
  tasks:
    - name: Uninstall Packages from the Servers
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - zabbix-agent
        - monit
        - zip
        - iftop
        - tar
        - software-properties-common
        - htop
        - lolcat
        - bzip2
        - vnstat
        - rsnapshot
        - git
        - whois
        - mysecureshell
        - mailutils
        - snapd
        - lynx
        - lz4
        - mawk
        - figlet
        - memcached
        - mime-support
        - mount
        - multipath-tools
        - mytop
        - net-tools
        - nmap
        - nodejs
        - npm
        - curl

    - name: Removing DevOps Custom Bash Profile
      file:
        path: /root/.bashrc
        state: absent

    - name: Reverting the server to Apache2
      template:
        src: templates/default_ports.conf.j2
        dest: /etc/apache2/ports.conf

    - name: Activating Web Services
      service:
        name: apache2
        state: restarted

    - name: Uninstall Web Services Packages
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - nginx
        - varnish 
        - redis

    - name: Removing Nginx and Varnish Configuration Files
      file:
        path: /etc/{{ item }}
        state: absent
      loop:
        - nginx
        - varnish
        - redis
