---
- name: Install Apache2 and PHP
  hosts: servers
  become: true
  #become_user: admin_user  # Specify the user with sudo privileges

  #vars:
    #ansible_become_pass: "123"
  tasks:
    - name: Add PHP PPA repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Install Apache2 modules
      apt:
        name:
          - apache2-bin
          - apache2-data
          - apache2-utils
          - libapache2-mod-php8.0
          - libapache2-mod-php8.1
          - libapache2-mod-php8.2
          - libapache2-mod-php8.3
        state: present

    - name: Enable required Apache & PHP modules
      command: "a2enmod {{ item }}"
      loop:
        - access_compat
        - ssl
        - alias
        - auth_basic
        - authn_core
        - authn_file
        - authz_core
        - authz_host
        - authz_user
        - autoindex
        - deflate
        - dir
        - env
        - expires
        - filter
        - headers
        - mime
        - mpm_prefork
        - negotiation
        - reqtimeout
        - rewrite
        - setenvif
        - status
        - php8.0
        - php8.0-fpm
        - php8.1
        - php8.1-fpm
        - php8.2
        - php8.2-fpm
        - php8.3
        - php8.3-fpm


    - name: Restart Apache2 service
      service:
        name: apache2
        state: restarted
