---
- name: Install packages on servers
  hosts: testing
  become: yes
  tasks:
    - name: UPDATING PACKAGE LISTS & UPGRADING INSTALLED PACKAGES
      apt:
        update_cache: 'yes'
        upgrade: 'yes'

    - name: INSTALLING COMMON PACKAGES
      apt:
        name:
          - zip
          - iftop
          - tar
          - software-properties-common
          - htop
          - lolcat
          - bzip2
          - vnstat
          - rsnapshot
          - git
          - whois
          - mysecureshell
          - mailutils
          - snapd
          - lynx
          - lz4
          - mawk
          - figlet
          - memcached
          - mime-support
          - mount
          - multipath-tools
          - mytop
          - net-tools
          - nmap
          - nodejs
          - npm
          - curl
        state: present
          
    - name:  Enabling Bash Profiling to remote Host
      copy: src={{item.src}} dest={{item.dest}} owner=root group=root mode=0644
      with_items:
       - { src: '/ddevops/ansible-playbooks/templates/root_bashrc.j2', dest: '/root/.bashrc' }
       - { src: '/ddevops/ansible-playbooks/templates/dircolors.j2', dest: '/root/.dircolors' }
       - { src: '/ddevops/ansible-playbooks/templates/user_bashrc.j2', dest: '/etc/skel/.bashrc' }
       - { src: '/ddevops/ansible-playbooks/templates/sftp_config.j2', dest: '/etc/ssh/sftp_config' }
