---
- name: Install Zabbix Agent
  hosts: servers
  become: true
  #vars:
    #ansible_become_pass: "lol" 
 tasks:
    - name: Download Zabbix repository package
      get_url:
        url: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-2+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release_5.0-2+ubuntu22.04_all.deb

    - name: Install Zabbix repository package
      apt:
        deb: /tmp/zabbix-release_5.0-2+ubuntu22.04_all.deb
        update_cache: yes

    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: present
        update_cache: yes
